version: '3'

services:
 httpd-micro:
#  build: ./dockerfile
# website:
  image: httpd
  volumes:
#    - ../javascript:/usr/local/apache2/htdocs/
    - ../javascript_es5:/usr/local/apache2/htdocs/
  ports:
    - 2001:80
  #depends_on:
  #  - build-service
